apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-python-flask
  labels:
    app: tool-python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool-python-flask
  template:
    metadata:
      labels:
        app: tool-python-flask
    spec:
      containers:
        - name: tool-python-flask
          image: 658721656416.dkr.ecr.ap-southeast-1.amazonaws.com/tools-python-flask
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      imagePullSecrets:
        - name: ecrdockersecret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tool-python-flask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tool-python-flask
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: tool-python-flask-svc
spec:
  selector:
    app: tool-python-flask
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer